[package]
name = "area"
version = "0.0.0-placeholder"
edition = "2024"

license = "BSD-2-Clause OR Apache-2.0 OR MIT"

authors = ["Peter Lyons Kehl<peter.kehl@gmail.com>"]
description = "zero copy mmap-friendly object graphs with index-based pointers/references"

categories = ["development-tools", "no-std", "rust-patterns"]

keywords = ["zerocopy"]

repository = "https://github.com/peter-lyons-kehl/area"
homepage = "https://github.com/peter-lyons-kehl/area"

[dependencies]
